/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FaqsRouteImport } from './routes/Faqs'
import { Route as InterstateCarTransportRouteImport } from './routes/Interstate-Car-Transport'
import { Route as JunkMovesRouteImport } from './routes/Junk-moves'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BookRouteImport } from './routes/book'
import { Route as CleaningRouteImport } from './routes/cleaning'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as HomeMovesRouteImport } from './routes/home-moves'
import { Route as HubRouteImport } from './routes/hub'
import { Route as InternationalRelocationsRouteImport } from './routes/international-relocations'
import { Route as MovingCompanyLagosRouteImport } from './routes/moving-company-lagos'
import { Route as OfficeMovesRouteImport } from './routes/office-moves'
import { Route as PartnerRouteImport } from './routes/partner'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as StorageRouteImport } from './routes/storage'
import { Route as StoreDeliveryRouteImport } from './routes/store-delivery'
import { Route as WeddingHandlingRouteImport } from './routes/wedding-handling'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqsRoute = FaqsRouteImport.update({
  id: '/Faqs',
  path: '/Faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const InterstateCarTransportRoute = InterstateCarTransportRouteImport.update({
  id: '/Interstate-Car-Transport',
  path: '/Interstate-Car-Transport',
  getParentRoute: () => rootRouteImport,
} as any)
const JunkMovesRoute = JunkMovesRouteImport.update({
  id: '/Junk-moves',
  path: '/Junk-moves',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const CleaningRoute = CleaningRouteImport.update({
  id: '/cleaning',
  path: '/cleaning',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeMovesRoute = HomeMovesRouteImport.update({
  id: '/home-moves',
  path: '/home-moves',
  getParentRoute: () => rootRouteImport,
} as any)
const HubRoute = HubRouteImport.update({
  id: '/hub',
  path: '/hub',
  getParentRoute: () => rootRouteImport,
} as any)
const InternationalRelocationsRoute =
  InternationalRelocationsRouteImport.update({
    id: '/international-relocations',
    path: '/international-relocations',
    getParentRoute: () => rootRouteImport,
  } as any)
const MovingCompanyLagosRoute = MovingCompanyLagosRouteImport.update({
  id: '/moving-company-lagos',
  path: '/moving-company-lagos',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficeMovesRoute = OfficeMovesRouteImport.update({
  id: '/office-moves',
  path: '/office-moves',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerRoute = PartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const StorageRoute = StorageRouteImport.update({
  id: '/storage',
  path: '/storage',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreDeliveryRoute = StoreDeliveryRouteImport.update({
  id: '/store-delivery',
  path: '/store-delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const WeddingHandlingRoute = WeddingHandlingRouteImport.update({
  id: '/wedding-handling',
  path: '/wedding-handling',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/Faqs': typeof FaqsRoute
  '/Interstate-Car-Transport': typeof InterstateCarTransportRoute
  '/Junk-moves': typeof JunkMovesRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/cleaning': typeof CleaningRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/home-moves': typeof HomeMovesRoute
  '/hub': typeof HubRoute
  '/international-relocations': typeof InternationalRelocationsRoute
  '/moving-company-lagos': typeof MovingCompanyLagosRoute
  '/office-moves': typeof OfficeMovesRoute
  '/partner': typeof PartnerRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/storage': typeof StorageRoute
  '/store-delivery': typeof StoreDeliveryRoute
  '/wedding-handling': typeof WeddingHandlingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/Faqs': typeof FaqsRoute
  '/Interstate-Car-Transport': typeof InterstateCarTransportRoute
  '/Junk-moves': typeof JunkMovesRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/cleaning': typeof CleaningRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/home-moves': typeof HomeMovesRoute
  '/hub': typeof HubRoute
  '/international-relocations': typeof InternationalRelocationsRoute
  '/moving-company-lagos': typeof MovingCompanyLagosRoute
  '/office-moves': typeof OfficeMovesRoute
  '/partner': typeof PartnerRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/storage': typeof StorageRoute
  '/store-delivery': typeof StoreDeliveryRoute
  '/wedding-handling': typeof WeddingHandlingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/Faqs': typeof FaqsRoute
  '/Interstate-Car-Transport': typeof InterstateCarTransportRoute
  '/Junk-moves': typeof JunkMovesRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/cleaning': typeof CleaningRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/home-moves': typeof HomeMovesRoute
  '/hub': typeof HubRoute
  '/international-relocations': typeof InternationalRelocationsRoute
  '/moving-company-lagos': typeof MovingCompanyLagosRoute
  '/office-moves': typeof OfficeMovesRoute
  '/partner': typeof PartnerRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/storage': typeof StorageRoute
  '/store-delivery': typeof StoreDeliveryRoute
  '/wedding-handling': typeof WeddingHandlingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/Faqs'
    | '/Interstate-Car-Transport'
    | '/Junk-moves'
    | '/about'
    | '/book'
    | '/cleaning'
    | '/contact'
    | '/gallery'
    | '/home-moves'
    | '/hub'
    | '/international-relocations'
    | '/moving-company-lagos'
    | '/office-moves'
    | '/partner'
    | '/services'
    | '/sitemap.xml'
    | '/storage'
    | '/store-delivery'
    | '/wedding-handling'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/Faqs'
    | '/Interstate-Car-Transport'
    | '/Junk-moves'
    | '/about'
    | '/book'
    | '/cleaning'
    | '/contact'
    | '/gallery'
    | '/home-moves'
    | '/hub'
    | '/international-relocations'
    | '/moving-company-lagos'
    | '/office-moves'
    | '/partner'
    | '/services'
    | '/sitemap.xml'
    | '/storage'
    | '/store-delivery'
    | '/wedding-handling'
  id:
    | '__root__'
    | '/'
    | '/Faqs'
    | '/Interstate-Car-Transport'
    | '/Junk-moves'
    | '/about'
    | '/book'
    | '/cleaning'
    | '/contact'
    | '/gallery'
    | '/home-moves'
    | '/hub'
    | '/international-relocations'
    | '/moving-company-lagos'
    | '/office-moves'
    | '/partner'
    | '/services'
    | '/sitemap.xml'
    | '/storage'
    | '/store-delivery'
    | '/wedding-handling'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FaqsRoute: typeof FaqsRoute
  InterstateCarTransportRoute: typeof InterstateCarTransportRoute
  JunkMovesRoute: typeof JunkMovesRoute
  AboutRoute: typeof AboutRoute
  BookRoute: typeof BookRoute
  CleaningRoute: typeof CleaningRoute
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRoute
  HomeMovesRoute: typeof HomeMovesRoute
  HubRoute: typeof HubRoute
  InternationalRelocationsRoute: typeof InternationalRelocationsRoute
  MovingCompanyLagosRoute: typeof MovingCompanyLagosRoute
  OfficeMovesRoute: typeof OfficeMovesRoute
  PartnerRoute: typeof PartnerRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StorageRoute: typeof StorageRoute
  StoreDeliveryRoute: typeof StoreDeliveryRoute
  WeddingHandlingRoute: typeof WeddingHandlingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Faqs': {
      id: '/Faqs'
      path: '/Faqs'
      fullPath: '/Faqs'
      preLoaderRoute: typeof FaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Interstate-Car-Transport': {
      id: '/Interstate-Car-Transport'
      path: '/Interstate-Car-Transport'
      fullPath: '/Interstate-Car-Transport'
      preLoaderRoute: typeof InterstateCarTransportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Junk-moves': {
      id: '/Junk-moves'
      path: '/Junk-moves'
      fullPath: '/Junk-moves'
      preLoaderRoute: typeof JunkMovesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cleaning': {
      id: '/cleaning'
      path: '/cleaning'
      fullPath: '/cleaning'
      preLoaderRoute: typeof CleaningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home-moves': {
      id: '/home-moves'
      path: '/home-moves'
      fullPath: '/home-moves'
      preLoaderRoute: typeof HomeMovesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub': {
      id: '/hub'
      path: '/hub'
      fullPath: '/hub'
      preLoaderRoute: typeof HubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/international-relocations': {
      id: '/international-relocations'
      path: '/international-relocations'
      fullPath: '/international-relocations'
      preLoaderRoute: typeof InternationalRelocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moving-company-lagos': {
      id: '/moving-company-lagos'
      path: '/moving-company-lagos'
      fullPath: '/moving-company-lagos'
      preLoaderRoute: typeof MovingCompanyLagosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/office-moves': {
      id: '/office-moves'
      path: '/office-moves'
      fullPath: '/office-moves'
      preLoaderRoute: typeof OfficeMovesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner': {
      id: '/partner'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof PartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/storage': {
      id: '/storage'
      path: '/storage'
      fullPath: '/storage'
      preLoaderRoute: typeof StorageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store-delivery': {
      id: '/store-delivery'
      path: '/store-delivery'
      fullPath: '/store-delivery'
      preLoaderRoute: typeof StoreDeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wedding-handling': {
      id: '/wedding-handling'
      path: '/wedding-handling'
      fullPath: '/wedding-handling'
      preLoaderRoute: typeof WeddingHandlingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FaqsRoute: FaqsRoute,
  InterstateCarTransportRoute: InterstateCarTransportRoute,
  JunkMovesRoute: JunkMovesRoute,
  AboutRoute: AboutRoute,
  BookRoute: BookRoute,
  CleaningRoute: CleaningRoute,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRoute,
  HomeMovesRoute: HomeMovesRoute,
  HubRoute: HubRoute,
  InternationalRelocationsRoute: InternationalRelocationsRoute,
  MovingCompanyLagosRoute: MovingCompanyLagosRoute,
  OfficeMovesRoute: OfficeMovesRoute,
  PartnerRoute: PartnerRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StorageRoute: StorageRoute,
  StoreDeliveryRoute: StoreDeliveryRoute,
  WeddingHandlingRoute: WeddingHandlingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
